jobs:
  build:
    docker:
      - images: rust:latest
    working_directory: /go/src/github.com/tkyk0317/rcc
    steps:
      - checkout
      - run:
        name: Run all tests
        command: cargo test --all